import express from 'express';
import https from 'https';
import fs from 'fs';
import path from 'path';
import os from 'os';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import { config } from './config/index.js';
import { appsRouter } from './routes/apps.routes.js';
import { selectionsRouter } from './routes/selections.routes.js';
import { adminRouter } from './routes/admin.routes.js';

const app = express();

// Use mkcert certificates (generated by vite-plugin-mkcert)
const mkcertDir = path.join(os.homedir(), '.vite-plugin-mkcert');
const keyPath = path.join(mkcertDir, 'dev.pem');
const certPath = path.join(mkcertDir, 'cert.pem');

let httpsOptions: { key: string; cert: string } | null = null;

if (fs.existsSync(keyPath) && fs.existsSync(certPath)) {
  httpsOptions = {
    key: fs.readFileSync(keyPath, 'utf-8'),
    cert: fs.readFileSync(certPath, 'utf-8'),
  };
  console.log('Using mkcert certificates from:', mkcertDir);
} else {
  console.warn('mkcert certificates not found. Run client dev server first to generate them.');
}

// Security headers
app.use(helmet({
  crossOriginResourcePolicy: { policy: 'cross-origin' },
  contentSecurityPolicy: config.isProduction ? undefined : false,
}));

// Rate limiting
const limiter = rateLimit({
  windowMs: config.rateLimit.windowMinutes * 60 * 1000,
  max: config.rateLimit.max,
  message: { error: 'คำขอมากเกินไป กรุณารอสักครู่' },
  standardHeaders: true,
  legacyHeaders: false,
});
app.use(limiter);

// CORS
app.use(cors({
  origin: config.corsOrigins,
  methods: ['GET', 'POST', 'PUT', 'DELETE'],
  allowedHeaders: ['Content-Type', 'Authorization'],
}));

// Body parsing with size limits
app.use(express.json({ limit: '1mb' }));
app.use(express.urlencoded({ extended: true, limit: '1mb' }));

// Routes
app.use('/api', appsRouter);
app.use('/api/selections', selectionsRouter);
app.use('/api/admin', adminRouter);

// Health check
app.get('/health', (_req, res) => {
  res.json({
    status: 'ok',
    timestamp: new Date().toISOString(),
    environment: config.nodeEnv,
  });
});

// Start server (HTTPS if certificates available, HTTP otherwise)
if (httpsOptions) {
  const httpsServer = https.createServer(httpsOptions, app);
  httpsServer.listen(config.port, () => {
    console.log(`Server running on https://localhost:${config.port}`);
    console.log(`Environment: ${config.nodeEnv}`);
  });
} else {
  // Fallback to HTTP if no certificates
  app.listen(config.port, () => {
    console.log(`Server running on http://localhost:${config.port} (no HTTPS certificates)`);
    console.log(`Environment: ${config.nodeEnv}`);
  });
}


